In [1]:
import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine
import numpy as np

## Hour 1: Loading and exploring data

### Loading data

In [2]:
connection_url = "postgresql+psycopg2://agrc:agrc@opensgid.ugrc.utah.gov:5432/opensgid"
connection = create_engine(connection_url)
sql = "SELECT * FROM recreation.parks_local"
parks = gpd.read_postgis(sql, connection, geom_col="shape")

In [3]:
parks

,xid,name,county,city,acres,type,status,shape
0,1,Lundstrom Park,CACHE,Logan,19.242154,Neighborhood Park,Complete,"MULTIPOLYGON (((434360.76 4622935.183, 434358...."
1,2,Ray Hugie Park,CACHE,Cache County,11.110399,Neighborhood Park,Current,"MULTIPOLYGON (((434742.921 4621660.675, 434679..."
2,3,Adams Park,CACHE,Logan,4.213980,Neighborhood Park,Current,"MULTIPOLYGON (((431562.728 4621521.427, 431557..."
3,4,River Hollow Park,CACHE,Logan,3.636311,Neighborhood Park,Current,"MULTIPOLYGON (((432566.396 4620878.806, 432554..."
4,5,Jens Johansen Park,CACHE,Logan,2.035590,Neighborhood Park,Current,"MULTIPOLYGON (((432330.614 4620582.489, 432324..."
...,...,...,...,...,...,...,...,...
2098,681,Cottonwood Grove Park,SALT LAKE,Murray,21.352288,Neighborhood Park,Complete,"MULTIPOLYGON (((422050.606 4499374.667, 422051..."
2099,1208,Park,UTAH,Highland City,10.452749,Park,Complete,"MULTIPOLYGON (((431822.619 4477940.783, 431822..."
2100,1869,Stansbury Park,TOOELE,None,10.878463,Community Park,None,"MULTIPOLYGON (((390426.581 4500486.442, 390472..."
2101,1943,Powerline Park,DAVIS,Clinton,13.184151,Community Park,None,"MULTIPOLYGON (((411198.573 4554739.585, 411270..."
2102,1975,Mountain View Estates park,DAVIS,Woods Cross,6.665397,Neighborhood Park,None,"MULTIPOLYGON (((421618.858 4524869.994, 421606..."

### Dataframes and Series

In [4]:
#: Get info about the dataframe
parks.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 2103 entries, 0 to 2102
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   xid     2103 non-null   int64
 1   name    2103 non-null   object
 2   county  2103 non-null   object
 3   city    2050 non-null   object
 4   acres   2102 non-null   float64
 5   type    2103 non-null   object
 6   status  1709 non-null   object
 7   shape   2103 non-null   geometry
dtypes: float64(1), geometry(1), int64(1), object(5)
memory usage: 131.6+ KB

In [5]:
#: Show a specific column
parks["name"]

0                   Lundstrom Park
1                   Ray Hugie Park
2                       Adams Park
3                River Hollow Park
4               Jens Johansen Park
                   ...
2098         Cottonwood Grove Park
2099                          Park
2100                Stansbury Park
2101                Powerline Park
2102    Mountain View Estates park
Name: name, Length: 2103, dtype: object

In [6]:
#: Get info about a specific column
parks["name"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2103 entries, 0 to 2102
Series name: name
Non-Null Count  Dtype
--------------  -----
2103 non-null   object
dtypes: object(1)
memory usage: 16.6+ KB

In [7]:
#: Use .loc to get a specific row
parks.loc[0]

xid                                                       1
name                                         Lundstrom Park
county                                                CACHE
city                                                  Logan
acres                                             19.242154
type                                      Neighborhood Park
status                                             Complete
shape     MULTIPOLYGON (((434360.75989999995 4622935.183...
Name: 0, dtype: object

### The Index

In [8]:
parks.index

RangeIndex(start=0, stop=2103, step=1)

In [9]:
parks_by_name = parks.set_index("name")
parks_by_name

,xid,county,city,acres,type,status,shape
name,,,,,,,
Lundstrom Park,1,CACHE,Logan,19.242154,Neighborhood Park,Complete,"MULTIPOLYGON (((434360.76 4622935.183, 434358...."
Ray Hugie Park,2,CACHE,Cache County,11.110399,Neighborhood Park,Current,"MULTIPOLYGON (((434742.921 4621660.675, 434679..."
Adams Park,3,CACHE,Logan,4.213980,Neighborhood Park,Current,"MULTIPOLYGON (((431562.728 4621521.427, 431557..."
River Hollow Park,4,CACHE,Logan,3.636311,Neighborhood Park,Current,"MULTIPOLYGON (((432566.396 4620878.806, 432554..."
Jens Johansen Park,5,CACHE,Logan,2.035590,Neighborhood Park,Current,"MULTIPOLYGON (((432330.614 4620582.489, 432324..."
...,...,...,...,...,...,...,...
Cottonwood Grove Park,681,SALT LAKE,Murray,21.352288,Neighborhood Park,Complete,"MULTIPOLYGON (((422050.606 4499374.667, 422051..."
Park,1208,UTAH,Highland City,10.452749,Park,Complete,"MULTIPOLYGON (((431822.619 4477940.783, 431822..."
Stansbury Park,1869,TOOELE,None,10.878463,Community Park,None,"MULTIPOLYGON (((390426.581 4500486.442, 390472..."
Powerline Park,1943,DAVIS,Clinton,13.184151,Community Park,None,"MULTIPOLYGON (((411198.573 4554739.585, 411270..."
Mountain View Estates park,1975,DAVIS,Woods Cross,6.665397,Neighborhood Park,None,"MULTIPOLYGON (((421618.858 4524869.994, 421606..."

In [10]:
#: Check if the index is unique
parks_by_name.index.is_unique

False

In [11]:
#: View duplicated index values
parks_by_name[parks_by_name.index.duplicated(keep=False)].sort_index()

,xid,county,city,acres,type,status,shape
name,,,,,,,
Anderson Park,1695,BOX ELDER,Perry,0.925934,City Park,Complete,"MULTIPOLYGON (((413775.145 4590338.295, 413784..."
Anderson Park,1187,UTAH,Pleasant Grove,4.844358,Park,Complete,"MULTIPOLYGON (((438894.446 4468388.151, 438834..."
Arrowhead Park,656,SALT LAKE,Murray,2.690243,Neighborhood Park,Complete,"MULTIPOLYGON (((423243.102 4502194.632, 423326..."
Arrowhead Park,676,SALT LAKE,Murray,30.964547,Neighborhood Park,Complete,"MULTIPOLYGON (((423294.188 4502184.183, 423217..."
Ball Park,1574,SUMMIT,Park City,8.704634,Park,Complete,"MULTIPOLYGON (((458118.498 4502176.397, 458096..."
...,...,...,...,...,...,...,...
Woodcove Park,797,SALT LAKE,West Jordan City,3.109195,Neighborhood Park,Complete,"MULTIPOLYGON (((418763.172 4495418.15, 418763...."
Woodcove Park,795,SALT LAKE,West Jordan City,1.997201,Neighborhood Park,Complete,"MULTIPOLYGON (((418640.165 4495546.614, 418646..."
Woodcove Park,794,SALT LAKE,West Jordan City,0.868016,Neighborhood Park,Complete,"MULTIPOLYGON (((418791.962 4495643.466, 418792..."
Woodland Park,434,DAVIS,Farmington,10.877976,Park,Complete,"MULTIPOLYGON (((425677.71 4536355.473, 425679...."
Woodland Park,1164,UTAH,Woodland Hills,9.716524,Park,Complete,"MULTIPOLYGON (((444104.416 4428155.396, 444105..."

### Selecting Data

In [12]:
#: .loc: selection by label
parks_by_name.loc["Flat Iron Mesa Park"]

xid                                                     546
county                                            SALT LAKE
city                                             Sandy City
acres                                             31.063621
type                                              City Park
status                                             Complete
shape     MULTIPOLYGON (((428685.6188000003 4494601.5238...
Name: Flat Iron Mesa Park, dtype: object

In [13]:
#: Get multiple dimensions with .loc
parks_by_name.loc["Flat Iron Mesa Park", "city"]

'Sandy City'

In [14]:
#: .iloc: selection by position
parks.iloc[0]

xid                                                       1
name                                         Lundstrom Park
county                                                CACHE
city                                                  Logan
acres                                             19.242154
type                                      Neighborhood Park
status                                             Complete
shape     MULTIPOLYGON (((434360.75989999995 4622935.183...
Name: 0, dtype: object

In [15]:
#: Multiple dimensions with slicing
parks.iloc[0, 3:]

city                                                  Logan
acres                                             19.242154
type                                      Neighborhood Park
status                                             Complete
shape     MULTIPOLYGON (((434360.75989999995 4622935.183...
Name: 0, dtype: object

In [16]:
#: []: shorthand for selecting columns by label
parks["city"]

0               Logan
1        Cache County
2               Logan
3               Logan
4               Logan
            ...
2098           Murray
2099    Highland City
2100             None
2101          Clinton
2102      Woods Cross
Name: city, Length: 2103, dtype: object

In [17]:
#: Can use a list of column names to select multiple columns
parks[["name", "city"]]

                            name           city
0                 Lundstrom Park          Logan
1                 Ray Hugie Park   Cache County
2                     Adams Park          Logan
3              River Hollow Park          Logan
4             Jens Johansen Park          Logan
...                          ...            ...
2098       Cottonwood Grove Park         Murray
2099                        Park  Highland City
2100              Stansbury Park           None
2101              Powerline Park        Clinton
2102  Mountain View Estates park    Woods Cross

[2103 rows x 2 columns]

In [18]:
#: Can also use a list of booleans to select rows
parks_head = parks.head()
parks_head

,xid,name,county,city,acres,type,status,shape
0,1,Lundstrom Park,CACHE,Logan,19.242154,Neighborhood Park,Complete,"MULTIPOLYGON (((434360.76 4622935.183, 434358...."
1,2,Ray Hugie Park,CACHE,Cache County,11.110399,Neighborhood Park,Current,"MULTIPOLYGON (((434742.921 4621660.675, 434679..."
2,3,Adams Park,CACHE,Logan,4.213980,Neighborhood Park,Current,"MULTIPOLYGON (((431562.728 4621521.427, 431557..."
3,4,River Hollow Park,CACHE,Logan,3.636311,Neighborhood Park,Current,"MULTIPOLYGON (((432566.396 4620878.806, 432554..."
4,5,Jens Johansen Park,CACHE,Logan,2.035590,Neighborhood Park,Current,"MULTIPOLYGON (((432330.614 4620582.489, 432324..."

In [19]:
parks_head[[True, False, True, True, True]]

,xid,name,county,city,acres,type,status,shape
0,1,Lundstrom Park,CACHE,Logan,19.242154,Neighborhood Park,Complete,"MULTIPOLYGON (((434360.76 4622935.183, 434358...."
2,3,Adams Park,CACHE,Logan,4.213980,Neighborhood Park,Current,"MULTIPOLYGON (((431562.728 4621521.427, 431557..."
3,4,River Hollow Park,CACHE,Logan,3.636311,Neighborhood Park,Current,"MULTIPOLYGON (((432566.396 4620878.806, 432554..."
4,5,Jens Johansen Park,CACHE,Logan,2.035590,Neighborhood Park,Current,"MULTIPOLYGON (((432330.614 4620582.489, 432324..."

In [20]:
#: We can use an equality operator to create a series of booleans whose index matches the dataframe
boolean_series = parks_head["city"] == "Logan"
boolean_series

0     True
1    False
2     True
3     True
4     True
Name: city, dtype: bool

In [21]:
parks_head[boolean_series]

,xid,name,county,city,acres,type,status,shape
0,1,Lundstrom Park,CACHE,Logan,19.242154,Neighborhood Park,Complete,"MULTIPOLYGON (((434360.76 4622935.183, 434358...."
2,3,Adams Park,CACHE,Logan,4.213980,Neighborhood Park,Current,"MULTIPOLYGON (((431562.728 4621521.427, 431557..."
3,4,River Hollow Park,CACHE,Logan,3.636311,Neighborhood Park,Current,"MULTIPOLYGON (((432566.396 4620878.806, 432554..."
4,5,Jens Johansen Park,CACHE,Logan,2.035590,Neighborhood Park,Current,"MULTIPOLYGON (((432330.614 4620582.489, 432324..."

In [22]:
#: Do it all in one step
parks_head[parks_head["city"] == "Logan"]

,xid,name,county,city,acres,type,status,shape
0,1,Lundstrom Park,CACHE,Logan,19.242154,Neighborhood Park,Complete,"MULTIPOLYGON (((434360.76 4622935.183, 434358...."
2,3,Adams Park,CACHE,Logan,4.213980,Neighborhood Park,Current,"MULTIPOLYGON (((431562.728 4621521.427, 431557..."
3,4,River Hollow Park,CACHE,Logan,3.636311,Neighborhood Park,Current,"MULTIPOLYGON (((432566.396 4620878.806, 432554..."
4,5,Jens Johansen Park,CACHE,Logan,2.035590,Neighborhood Park,Current,"MULTIPOLYGON (((432330.614 4620582.489, 432324..."

In [23]:
parks[parks["county"] == "KANE"]

,xid,name,county,city,acres,type,status,shape
266,267,Sports Park,KANE,Kanab,12.703386,Park,Complete,"MULTIPOLYGON (((363853.13 4100453.38, 363851.7..."
267,268,Ball Park,KANE,Kanab,6.309854,Park,Complete,"MULTIPOLYGON (((363842.819 4100063.244, 363837..."
268,269,Park,KANE,Kanab,5.215228,Park,Complete,"MULTIPOLYGON (((364058.894 4100028.616, 364058..."
269,270,Park,KANE,Kanab,14.598555,Park,Complete,"MULTIPOLYGON (((364974.892 4099100.707, 364974..."
270,271,Park,KANE,Kanab,3.577798,Park,Complete,"MULTIPOLYGON (((363968.334 4101452.131, 363921..."
271,272,Sports Park,KANE,Kanab,14.417038,Park,Complete,"MULTIPOLYGON (((364304.844 4102427.712, 364111..."
272,273,Park,KANE,Orderville,1.970627,Park,Complete,"MULTIPOLYGON (((354912.791 4126626.666, 354910..."
273,274,Park,KANE,Orderville,1.672731,Park,Complete,"MULTIPOLYGON (((355406.871 4126805.424, 355492..."
274,275,Ball Park,KANE,Orderville,4.102748,Park,Complete,"MULTIPOLYGON (((354543.318 4127060.637, 354648..."
275,276,Ball Park,KANE,Glendale,1.696415,Park,Complete,"MULTIPOLYGON (((358766.233 4130699.404, 358800..."

### Where clauses

In [24]:
#: You can do where-style queries with .query() as well
parks.query("county == 'KANE'")

,xid,name,county,city,acres,type,status,shape
266,267,Sports Park,KANE,Kanab,12.703386,Park,Complete,"MULTIPOLYGON (((363853.13 4100453.38, 363851.7..."
267,268,Ball Park,KANE,Kanab,6.309854,Park,Complete,"MULTIPOLYGON (((363842.819 4100063.244, 363837..."
268,269,Park,KANE,Kanab,5.215228,Park,Complete,"MULTIPOLYGON (((364058.894 4100028.616, 364058..."
269,270,Park,KANE,Kanab,14.598555,Park,Complete,"MULTIPOLYGON (((364974.892 4099100.707, 364974..."
270,271,Park,KANE,Kanab,3.577798,Park,Complete,"MULTIPOLYGON (((363968.334 4101452.131, 363921..."
271,272,Sports Park,KANE,Kanab,14.417038,Park,Complete,"MULTIPOLYGON (((364304.844 4102427.712, 364111..."
272,273,Park,KANE,Orderville,1.970627,Park,Complete,"MULTIPOLYGON (((354912.791 4126626.666, 354910..."
273,274,Park,KANE,Orderville,1.672731,Park,Complete,"MULTIPOLYGON (((355406.871 4126805.424, 355492..."
274,275,Ball Park,KANE,Orderville,4.102748,Park,Complete,"MULTIPOLYGON (((354543.318 4127060.637, 354648..."
275,276,Ball Park,KANE,Glendale,1.696415,Park,Complete,"MULTIPOLYGON (((358766.233 4130699.404, 358800..."

### Exploring the data

In [42]:
#: What are the unique cities represented?
parks["city"].unique()

array(['Logan', 'Cache County', 'Providence', 'Smithfield', 'Richmond',
       'Amalga', 'Newton', 'Clarkston', 'North Logan', 'Hyde Park',
       'Millville', 'Paradise', 'Nibley', 'Mendon', 'Wellsville', 'Hyrum',
       'River Heights', 'Castle Dale', 'Cleveland', 'Clawson', 'Elmo',
       'Emery', 'Ferron', 'Green River', 'Huntington City',
       'Orangeville City', 'Grand County', 'Moab', 'Cedar City',
       'Richfield', 'Helper', 'Carbon County', 'Price', 'Wellington',
       'East Carbon', 'Hurricane', 'Ivins', 'Washington City',
       'Saint George', 'Milford', 'Willard', 'Garland', 'Tremonton',
       'Bear River City', 'Sunnyside', 'Nephi', 'Juab County', 'Oak City',
       'Manti', 'Gunnison ', 'Centerfield', 'Santa Clara', 'Redmond',
       'Blanding', 'Fillmore', 'Delta', 'Beaver', 'Minersville', 'Meadow',
       'Holden', 'Scipio', 'Lynndyl', 'Hinckley', 'Kanab', 'Orderville',
       'Glendale', 'Tropic', 'Bryce Canyon', 'Panguitch', 'Antimony',
       'Circleville', 'Junction', 'Marysvale', 'Torrey', 'Wayne County',
       'Bicknell', 'Lyman', 'Loa', 'Hanksville', 'Monticello',
       'Koosharem', 'Monroe', 'Joseph', 'Elsinore', 'Central Valley',
       'Glenwood', 'Aurora', 'Salina', 'Mayfield', 'Gunnison', 'Manit',
       'Ephraim', 'Spring City', 'Mt. Pleasant', 'Wales', 'Moroni',
       'Naples', 'Uintah County', 'Vernal', 'Ballard', 'Roosevelt',
       'Myton', 'Duchesne', 'Woodruff', 'Randolph', 'Laketown',
       'Garden City', 'Beaver County', 'Annabella', 'Centerville',
       'Farmington', 'Layton', 'Morgan County', 'Milton', 'Morgan City',
       'Draper', 'Salt Lake County', 'Riverton', 'Cottonwood Heights',
       'Midvale', 'Sandy City', 'Taylorsville', 'West Valley City',
       'West Jordan City', 'South Salt Lake', 'Salt Lake City',
       'South Jordan', 'Herriman', 'Murray', 'Bluffdale', 'Holladay',
       'Grantsville', 'Tooele', 'Lehi', 'Utah County', 'Orem',
       'Spanish Fork', 'Pleasant Grove', 'Springville', 'Eagle Mountain',
       'Alpine', 'Highland City', 'Saratoga Springs', 'Provo', 'Payson',
       'Fairfield', 'American Fork', 'Mapleton', 'Cedar Hills',
       'Cedar Fort', 'Goshen', 'Salem', 'Santaquin', 'Lindon',
       'Woodland Hills', 'Genola', 'Vineyard', 'Elk Ridge', 'Heber City',
       'Ogden', 'Riverdale', 'Washington Terrace', 'South Ogden', 'Roy',
       'West Haven', 'Unitah', 'Marriott-Slatterville', 'Weber County',
       'Plain City', 'Huntsville', 'North Ogden', 'Pleasant View',
       'Fruit Heights', 'Clinton', 'Clearfield', 'Syracuse',
       'Woods Cross', 'West Bountiful', 'West Point', 'North Salt Lake',
       'South Weber', 'Sunset', 'Bountiful', 'Brigham City', 'Coalville',
       'Kamas', 'Wasatch County', 'Midway', 'Oakley', 'Park City',
       'Summit County', 'West Jordan', 'Kearns', 'West Valley',
       'Millcreek', 'Kaysville', 'Hooper', 'Farr West', 'Warren', 'Perry',
       None, 'Highland', 'Lake Point', 'Charleston', 'Harrisville',
       'Marriott-Slaterville'], dtype=object)

In [45]:
#: How many unique cities are there?
parks["city"].nunique()

205

In [46]:
#: How many parks are in each city?
parks["city"].value_counts()

city
Salt Lake City      146
Saratoga Springs     89
South Jordan         76
Eagle Mountain       67
Lehi                 55
                   ...
Genola                1
West Bountiful        1
Warren                1
Charleston            1
Harrisville           1
Name: count, Length: 205, dtype: int64

### Vectorized Operations

The key to understanding pandas operations is to think in terms of **operations that are applied to every element in a vector**, rather than extracting each element and passing it to the operation one by one.

In [25]:
#: Standard python: we're responsible for looping through a vector and calling a function on each element:
for element in [1, 2, 3]:
    print(np.sqrt(element))

1.0
1.4142135623730951
1.7320508075688772

![for loop](assets/for_loop.png)

In [26]:
#: Vectorized operation: pass a whole vector to a vectorized function:
np.sqrt([1, 2, 3])

array([1.        , 1.41421356, 1.73205081])

In [27]:
#: pandas operation: a method on a series or dataframe
pd.Series([1, 2, 3]).transform(np.sqrt)

0    1.000000
1    1.414214
2    1.732051
dtype: float64

![vectorized](assets/vectorized_sqrt.png)

`for` loops in python are **computationally expensive** and require extra resources to set up the iteration. In addition, the function has to be called multiple times, requiring even more work behind the scenes for each call.

In contrast, vectorized operations are **optimized to perform the same operation on multiple pieces of data**. In addition to avoiding the overhead from iteration and multiple function calls, the processor has special logic and routines for parallelizing many operations. However, to use these it needs to know the operation and the data type ahead of time, which it generally can't with python `for` loops.

![take them all](assets/take_them_all.jpg)

### Think about sending a set of data to an operation, not operating on data one piece at a time.

In [28]:
#: Let's get the floor of the area of each park
parks["acres"].transform(np.floor)

0       19.0
1       11.0
2        4.0
3        3.0
4        2.0
        ...
2098    21.0
2099    10.0
2100    10.0
2101    13.0
2102     6.0
Name: acres, Length: 2103, dtype: float64

In [29]:
#: Many string ops are vectorized as well. Let's fix the case of the county names:
parks["county"].str.title()

0           Cache
1           Cache
2           Cache
3           Cache
4           Cache
          ...
2098    Salt Lake
2099         Utah
2100       Tooele
2101        Davis
2102        Davis
Name: county, Length: 2103, dtype: object

In [30]:
#: transform operations take in a series, operate on each element, and return a series of the same size. 
#: If we want to use all the values in a series to compute a single value, we can use an aggregation operation instead.
parks["acres"].agg("mean")

np.float64(10.253192668972407)

In [ ]:
#: A combination of 
parks.describe()

               xid        acres
count  2103.000000  2102.000000
mean   1052.000000    10.253193
std     607.228128    37.279791
min       1.000000     0.012419
25%     526.500000     1.396494
50%    1052.000000     3.886225
75%    1577.500000     9.009738
max    2103.000000  1022.557577

In [32]:
parks["acres"].mean()

np.float64(10.253192668972407)

## Hour 2: Analyzing and Manipulating Data

- Data types/missing data
- groupby
  - group parks by city, get total/average acreage
  - pull in municipal boundaries, calculate percentage of city area that is park

### Data Types and Missing Data

In [33]:
# bb_data = pd.read_csv(r"C:\gis\git\presentations\UGIC\2023\pandas\data\fcc\bdc_49_Cable_fixed_broadband_063022.csv")

In [34]:
# bb_data.head()

In [35]:
# bb_data.info()

In [36]:
parks.head()

,xid,name,county,city,acres,type,status,shape
0,1,Lundstrom Park,CACHE,Logan,19.242154,Neighborhood Park,Complete,"MULTIPOLYGON (((434360.76 4622935.183, 434358...."
1,2,Ray Hugie Park,CACHE,Cache County,11.110399,Neighborhood Park,Current,"MULTIPOLYGON (((434742.921 4621660.675, 434679..."
2,3,Adams Park,CACHE,Logan,4.213980,Neighborhood Park,Current,"MULTIPOLYGON (((431562.728 4621521.427, 431557..."
3,4,River Hollow Park,CACHE,Logan,3.636311,Neighborhood Park,Current,"MULTIPOLYGON (((432566.396 4620878.806, 432554..."
4,5,Jens Johansen Park,CACHE,Logan,2.035590,Neighborhood Park,Current,"MULTIPOLYGON (((432330.614 4620582.489, 432324..."

In [ ]:
#: Show me all rows where we don't have a value for city
parks[parks["city"].isna()]

,xid,name,county,city,acres,type,status,shape
1714,1717,Lake Shore Park,UTAH,None,6.996110,Special Use Park,None,"MULTIPOLYGON (((437768.235 4441746.224, 437768..."
1720,1723,Lincoln Beach,UTAH,None,17.751152,Community Park,None,"MULTIPOLYGON (((431477.371 4443965.277, 431483..."
1768,1771,Harbor Village Retention Park,UTAH,None,1.096866,Mini Park,None,"MULTIPOLYGON (((431789.896 4468133.057, 431785..."
1769,1772,Spring Creek Parkway,UTAH,None,6.375498,Neighborhood Park,None,"MULTIPOLYGON (((429109.383 4468642.278, 429113..."
1770,1773,Spring Creek Park,UTAH,None,12.556999,Community Park,None,"MULTIPOLYGON (((428878.553 4468328.129, 428882..."
1772,1775,Snow Springs Park,UTAH,None,0.497083,Mini Park,None,"MULTIPOLYGON (((424968.595 4469459.106, 424908..."
1811,1814,Broadmoor Park,UTAH,None,0.905231,Mini Park,None,"MULTIPOLYGON (((428862.852 4470656.884, 428861..."
1813,1816,Temple Meadows Park,UTAH,None,2.300436,Neighborhood Park,None,"MULTIPOLYGON (((435027.624 4471200.755, 435006..."
1817,1820,The Exchange Park,UTAH,None,5.300527,Neighborhood Park,None,"MULTIPOLYGON (((422931.1 4473696.634, 422927.3..."
1818,1821,Cranberry Farms HOA Park,UTAH,None,1.525615,Mini Park,None,"MULTIPOLYGON (((424564.078 4474518.578, 424487..."
1819,1822,Thanksgiving Point Trailhead,UTAH,None,1.522936,Neighborhood Park,None,"MULTIPOLYGON (((424300.808 4474470.683, 424298..."
1827,1830,Firehouse Park,UTAH,None,0.682795,Mini Park,None,"MULTIPOLYGON (((427662.941 4474814.586, 427662..."
1828,1831,Thanksgiving Point Electric Park,UTAH,None,10.110290,Community Park,None,"MULTIPOLYGON (((424714.541 4474858.492, 424852..."
1829,1832,Ivory Ridge Splash Pad,UTAH,None,9.614922,Community Park,None,"MULTIPOLYGON (((427158.072 4475602.737, 427156..."
1830,1833,Water Drainage Park,UTAH,None,0.537877,Green Space,None,"MULTIPOLYGON (((426893.821 4475693.016, 426861..."
1831,1834,Flood Control,UTAH,None,0.236570,Green Space,None,"MULTIPOLYGON (((426693.633 4475851.418, 426658..."
1832,1835,Triumph Park,UTAH,None,4.493047,Neighborhood Park,None,"MULTIPOLYGON (((425554.84 4476743.607, 425479...."
1833,1836,Sunrise Summit Park,UTAH,None,1.753745,Neighborhood Park,None,"MULTIPOLYGON (((424377.587 4477557.892, 424373..."
1834,1837,Flight Park State Recreation Area,UTAH,None,134.036466,Community Park,None,"MULTIPOLYGON (((423609.614 4479054.549, 423609..."
1866,1870,Gateway Park,TOOELE,None,0.830659,Mini Park,None,"MULTIPOLYGON (((390785.342 4500643.545, 390737..."
1882,1886,Cobblestone Park,WASATCH,None,15.613877,Community Park,None,"MULTIPOLYGON (((467397.103 4482882.74, 467397...."
1897,1901,Matt Knoop Memorial Park,SUMMIT,None,20.698813,Community Park,None,"MULTIPOLYGON (((454262.002 4504633.434, 454221..."
1898,1902,Spring Creek Trailhead,SUMMIT,None,0.731777,Mini Park,None,"MULTIPOLYGON (((454703.053 4508673.359, 454706..."
1899,1903,Jeremy Tennis Court,SUMMIT,None,0.159573,Special Use Park,None,"MULTIPOLYGON (((451991.414 4511970.967, 451986..."
1912,1916,Washington Park (Upper),SALT LAKE,None,10.106775,Community Park,None,"MULTIPOLYGON (((441802.04 4510702.158, 441870...."
1913,1917,Washington Park (Lower),SALT LAKE,None,4.932698,Neighborhood Park,None,"MULTIPOLYGON (((441493.163 4511371.988, 441464..."
1917,1921,Willard Park,BOX ELDER,None,29.798682,Community Park,None,"MULTIPOLYGON (((413928.264 4585045.497, 413885..."
1918,1922,Willard Children's Park,BOX ELDER,None,1.068282,Mini Park,None,"MULTIPOLYGON (((413801.548 4583803.004, 413803..."
1922,1926,North Ogden Park,WEBER,None,11.938373,Community Park,None,"MULTIPOLYGON (((419355.083 4573467.349, 419355..."
1923,1927,Bicentennial Park,WEBER,None,1.152585,Neighborhood Park,None,"MULTIPOLYGON (((418855.878 4573298.343, 418855..."
1928,1932,Reese Park,WEBER,None,5.699692,Neighborhood Park,None,"MULTIPOLYGON (((403663.418 4566998.507, 403664..."
1943,1948,Grey Hawk Park,DAVIS,None,10.197800,Community Park,None,"MULTIPOLYGON (((422321.351 4551488.552, 422321..."
1947,1952,Heritage Square,DAVIS,None,2.849495,Neighborhood Park,None,"MULTIPOLYGON (((417493.255 4548400.255, 417536..."
1951,1956,Bamberger Trail,DAVIS,None,5.858898,Green Space,None,"MULTIPOLYGON (((418767.513 4546320.996, 418741..."
1952,1957,Harmony Place Park,DAVIS,None,11.736764,Community Park,None,"MULTIPOLYGON (((414729.194 4545603.941, 414726..."
2001,2007,Arbor Park,SALT LAKE,None,0.109360,Green Space,None,"MULTIPOLYGON (((407787.764 4505416.504, 407787..."
2002,2008,Elk Run Park,SALT LAKE,None,3.046969,Green Space,None,"MULTIPOLYGON (((407352.827 4504966.146, 407352..."
2011,2017,Bruce Field Park,SALT LAKE,None,3.688685,Neighborhood Park,None,"MULTIPOLYGON (((416103.225 4501925.924, 416103..."
2012,2018,Paul F. Walker 9-11 Memorial Park,SALT LAKE,None,0.488687,Green Space,None,"MULTIPOLYGON (((414933.459 4500725.258, 414807..."
2013,2019,Kearns Linear Parkway,SALT LAKE,None,4.676333,Green Space,None,"MULTIPOLYGON (((415747.417 4500673.314, 415747..."
2014,2020,Hayes Conservation Garden,SALT LAKE,None,0.475182,Mini Park,None,"MULTIPOLYGON (((412824.929 4499155.504, 412916..."
2033,2039,Jefferson Place Condominiums,SALT LAKE,None,7.010199,Green Space,None,"MULTIPOLYGON (((423032.072 4493127.224, 422979..."
2034,2040,Porter Rockwell Trail,SALT LAKE,None,5.386073,Green Space,None,"MULTIPOLYGON (((424994.088 4492566.349, 424994..."
2065,2071,Day Care childrens park,SUMMIT,None,0.036332,Mini Park,None,"MULTIPOLYGON (((453007.801 4503940.706, 453006..."
2066,2072,Liberty Park,WEBER,None,9.398175,Community Park,None,"MULTIPOLYGON (((427924.63 4576115.858, 427916...."
2074,2080,Willow Point Clubhouse,UTAH,None,1.208152,Mini Park,None,"MULTIPOLYGON (((422452.064 4473736.583, 422452..."
2077,2083,Soldier Creek Dam Day Use Area,WASATCH,None,11.584544,Linear Park,None,"MULTIPOLYGON (((497486.979 4442885.936, 497515..."
2082,2088,Osier Park,UTAH,None,11.545731,Community Park,None,"MULTIPOLYGON (((423960.421 4471592.972, 424004..."
2083,2089,Meadowview Park,UTAH,None,2.865849,Neighborhood Park,None,"MULTIPOLYGON (((430475.439 4471037.408, 430464..."
2085,2091,Monarch Park,UTAH,None,2.538152,Neighborhood Park,None,"MULTIPOLYGON (((431237.632 4469021.452, 431237..."
2091,2097,Bamberger Park,UTAH,None,4.511239,Neighborhood Park,None,"MULTIPOLYGON (((434361.605 4469392.566, 434358..."
2092,2098,Trailside Park North,SUMMIT,None,17.935271,Community Park,None,"MULTIPOLYGON (((457628.777 4506860.742, 457629..."
2100,1869,Stansbury Park,TOOELE,None,10.878463,Community Park,None,"MULTIPOLYGON (((390426.581 4500486.442, 390472..."

In [39]:
#: How many are there?
len(parks[parks["city"].isna()])

53

In [ ]:
#: What about the good ones?
len(parks[parks["city"].notna()])

2050

In [41]:
#: We can also negate a condition with ~
len(parks[~parks["city"].isna()])

2050